Feature/log viewer
e-m-b-a/embark pull request #158
Opened 2023-09-30 14:38 UTC by 0x6368

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

**What is the current behavior?** (You can also link to an open issue here)
Opening the logs, downloads the whole log file (even if it it multiple megabytes in size)

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
Opening the logs opens a log viewer, that only loads the last lines of the logs. You can scroll through the logs by using the arrow keys or pgup/pgdown keys
![image](https://github.com/e-m-b-a/embark/assets/7045209/b4e11bde-da6d-4e72-b566-7dad7013eb91)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
A little bit? The option to download logs has moved to the log viewer instead of the report overview. The report overview will only link to the new log viewer

**Other information**:
---

2023-09-30 18:33 UTC, 0x6368 commented
I'll fix the linter issues in the coming days

2023-09-30 20:41 UTC, 0x6368 commented
I tried installing watchdog, but somehow it cannot lock the pipfile:

```
ubuntu@ubuntu-virtual-machine:~/embark$ pipenv install watchdog
Loading .env environment variables...
Installing watchdog...
Resolving watchdog...
Added watchdog to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock (8a1083) out of date, updating to (78152a)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠼ Locking...False
ERROR:pip.subprocessor:[present-rich] Getting requirements to build wheel exited with 1
[ResolutionFailure]:   File "/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py", line 897, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:   File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py", line 670, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py", line 447, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Getting requirements to build wheel exited with 1
```

2023-10-01 05:38 UTC, BenediktMKuehne commented
Oh that's always fun when that happens.😬

One of the packages has a dependency conflict with your new one.
Quite possibly the wsgi.
You could try forcing a newer version for the dependency

2023-10-01 07:12 UTC, 0x6368 commented
Looks like this was an issue with mysqlclient. This helped my install watchdog: https://forum.codewithmosh.com/t/pipenv-install-mysql-client/20899/4

In my case, I had to change the environment variables a little:

```bash
export MYSQLCLIENT_LDFLAGS='-L/usr/mysql/lib -lmysqlclient -lssl -lcrypto -lresolv'
export MYSQLCLIENT_CFLAGS='-I/usr/include/mysql/'
```

2023-10-02 08:10 UTC, BenediktMKuehne commented
will be testing the changes now

2023-10-05 12:56 UTC, BenediktMKuehne requested changes

2023-10-05 12:56 UTC, BenediktMKuehne commented on installer.sh
> +    wget -O ./embark/static/external/scripts/base64.js https://cdn.jsdelivr.net/npm/js-base64@3.7.5/+esm
Can we add these two lines to the developer install function too, please
line 424 for example

2023-10-05 12:58 UTC, BenediktMKuehne commented
Result is looking great 👍 
(sorry it took so long, I forgot to send/finalize the review)

2023-10-06 06:39 UTC, 0x6368 commented on installer.sh
> +    wget -O ./embark/static/external/scripts/base64.js https://cdn.jsdelivr.net/npm/js-base64@3.7.5/+esm
Done

2023-10-06 11:16 UTC, BenediktMKuehne approved these changes

2023-10-06 11:17 UTC, BenediktMKuehne commented
Nice work!

2023-10-06 11:17 UTC, merged