Installer for release versions
e-m-b-a/embark pull request #185
Opened 2023-12-19 12:26 UTC by BenediktMKuehne

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---

**What is the current behavior?** (You can also link to an open issue here)
---

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---

**Other information**:
---

2024-01-16 09:37 UTC, m-1-k-3 requested changes
sorry for the delay ... I have missed this PR

2024-01-16 09:37 UTC, m-1-k-3 commented on installer.sh
> +  if [[ "${NO_GIT}" -eq 1 && ${REFORCE} -eq 0 ]]; then
Please ensure consistent quoting

```
if [[ "${NO_GIT}" -eq 1 && "${REFORCE}" -eq 0 ]]; then
```

2024-01-16 09:37 UTC, m-1-k-3 commented on installer.sh
> +    if [[ ${REFORCE} -eq 1 ]]; then
please quote

2024-01-22 09:45 UTC, HoxhaEndri approved these changes
I tested the installation and everything works fine. Just add the quotations like Mike wrote.

2024-02-01 13:53 UTC, m-1-k-3 approved these changes

2024-02-01 13:53 UTC, merged