Strict mode
e-m-b-a/embark pull request #53
Opened 2022-08-19 07:18 UTC by BenediktMKuehne

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---
Add strict mode to EMBArk installer

**What is the current behavior?** (You can also link to an open issue here)
---
Bugs 😞 

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---
Catch some errors

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---
nope ❎ 

**Other information**:
---

2022-08-23 19:06 UTC, m-1-k-3 commented on installer.sh
> +  userdel www-embark || true
could we do a quick check if the user is on the host? like this pseudo code?
If ! grep www-embark /etc/passwd; then
userdel
fi

2022-08-23 19:07 UTC, m-1-k-3 commented on installer.sh
> +  rm ./.env || true
please always check if the file is available before doing something with it:
if [[ -f ./.env ]]; then
rm
fi

2022-08-23 19:08 UTC, m-1-k-3 commented on installer.sh
> +  docker network rm emba_runs || true
could we check if the network device is available before trying to remove it?

2022-08-23 19:08 UTC, m-1-k-3 commented on installer.sh
> +  systemctl stop embark.service || true
could we do a check if the service is running?

2022-08-23 19:09 UTC, m-1-k-3 commented on run-server.sh
> +cp -u "$PWD"/cert/embark.local.crt /var/www/conf/cert
please do a check if the files are available

2022-08-23 19:09 UTC, m-1-k-3 commented on installer.sh
> +REFORCE=0
are these exports or locals? Pls define here for clarification.

2022-08-23 19:10 UTC, m-1-k-3 requested changes
looks quite good. Please review my comments. AFterwards I will do another installation

2022-08-25 13:32 UTC, BenediktMKuehne commented
@m-1-k-3  should be ready for another round

2022-08-26 19:50 UTC, m-1-k-3 commented on helper/helper_embark_general.sh
> +  local IMAGE_NAME_="$1"
for init an empty var in your local function ${1:-} will do the job:

local IMAGE_NAME_="${1:-}"

2022-08-26 19:50 UTC, m-1-k-3 commented on helper/helper_embark_general.sh
> +  local IMAGE_VERSION_="$2"
init this var with ${2:-}

2022-08-26 19:50 UTC, m-1-k-3 commented on helper/helper_embark_general.sh
> +  local NET_ID
init this var with
local NET_ID=""

2022-08-26 19:52 UTC, m-1-k-3 commented on helper/helper_embark_general.sh
> +  if docker network ls | grep -E "$1"; then
please start setting up the vars in the beginning of the func. E.g.
local NAME_OF_VAR="${1:-}"

2022-08-26 19:53 UTC, m-1-k-3 commented on helper/helper_embark_general.sh
> +  # $1 : source
please init the vars here
local SOURCE="${1:-}"
local DEST="${2:-}"

2022-08-26 19:55 UTC, m-1-k-3 commented on helper/helper_embark_general.sh
> +  local STRICT_MODE_="$1"
see here https://github.com/m-1-k-3/emba/blob/5a0a58b76b81ba42d75bc4efbadb6589e0a886b1/helpers/helpers_emba_helpers.sh#L185

2022-08-26 19:56 UTC, m-1-k-3 commented on installer.sh
> +  local RANDOM_PW
local RANDOM_PW=""

2022-08-26 19:56 UTC, m-1-k-3 commented on installer.sh
> +  local DJANGO_SECRET_KEY
init
local DJANGO_SECRET_KEY=""

2022-08-26 19:57 UTC, m-1-k-3 commented on installer.sh
> +  local DOCKER_COMP_VER
=""

2022-08-26 20:00 UTC, m-1-k-3 commented
a few late notes for this PR. Will do a fresh install during the weekend ...

2022-08-28 20:22 UTC, m-1-k-3 approved these changes

2022-08-28 20:22 UTC, merged