Porter
e-m-b-a/embark pull request #68
Opened 2022-11-11 08:14 UTC by BenediktMKuehne

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
---
Importing
Exporting
Log-download
UI-changes
Bug-fixes

**What is the current behavior?** (You can also link to an open issue here)
---
Log-download not working
Cluttered UI

**What is the new behavior (if this is a feature change)? If possible add a screenshot.**
---
TODO

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
---
No

2023-01-23 15:07 UTC, BenediktMKuehne commented
`git clone https://github.com/BenediktMKuehne/embark.git -b porter`

2023-01-25 10:51 UTC, m-1-k-3 commented
Monster PR ... starting with an installation

2023-01-25 21:22 UTC, torabi12 commented
I just did a short test on Ubuntu server today, and the installation and test run were OK. I was able to dowload the logs from EMBArk. The main dashboard remained empty after the scan:
![kép](https://user-images.githubusercontent.com/98665813/214693678-77bdf2f5-324c-407c-acca-89209d63f58b.png)

[install.txt](https://github.com/e-m-b-a/embark/files/10503775/install.txt)
[run-server.txt](https://github.com/e-m-b-a/embark/files/10503776/run-server.txt)

I am going to wait for the final release, I just wanted to test the actual version.

2023-01-26 13:32 UTC, BenediktMKuehne commented
There is an issue with formatting the vulnerabilities for rendering.
Will check and fix

2023-01-26 14:10 UTC, BenediktMKuehne commented
fixed

2023-02-07 17:35 UTC, torabi12 commented
I tried again the porter version and when I started the scan the browser was waiting a few sec and I got timeout:
![kép](https://user-images.githubusercontent.com/98665813/217320922-5c00f12c-7595-44b3-af04-85db3507a034.png)

I was just curious about its current state.

2023-02-07 18:27 UTC, m-1-k-3 commented
Could you please check this again? My last tests were not running into this issue

2023-02-10 07:31 UTC, torabi12 commented
I tried it again but it does not download the CVE database now. I have seen this before, maybe later will be ok.

2023-02-10 08:32 UTC, m-1-k-3 commented
Probably this one? https://github.com/e-m-b-a/emba/issues/480

2023-02-10 09:29 UTC, m-1-k-3 requested changes
check this

2023-02-10 09:29 UTC, m-1-k-3 commented on dev-tools/debug-server-start.sh
> +# fi
why removed this check?

2023-02-10 09:29 UTC, m-1-k-3 commented on run-server.sh
> +if ! (cd "$PWD"/emba && ./emba.sh -d); then
emba without .sh

2023-02-10 09:53 UTC, torabi12 commented
> Probably this one? [e-m-b-a/emba#480](https://github.com/e-m-b-a/emba/issues/480)

[install.txt](https://github.com/e-m-b-a/embark/files/10706015/install.txt)
Could you please check my installation logs at the end?

I use Ubuntu Server
VERSION="22.04.1 LTS (Jammy Jellyfish)"

I think the CVE download section is competly missing on my side now:(
Thank you.

2023-02-10 10:03 UTC, m-1-k-3 commented
```
[1mInstalling libssl1.1 for mongodb![0m
------------------------------------------------------------------------------------------------
Error detected - status code [0;33m8[0m
Command:  [0;33mecho -e "Command:  $ORANGE$BASH_COMMAND$NC"[0m
Location:  [0;33m./installer/ID1_ubuntu_os.sh[0m, line [0;33m42[0m
Stack Trace:
    [1] ID1_ubuntu_os(): ./installer/ID1_ubuntu_os.sh, line 42 -> ID1_ubuntu_os
    [2] main(): ./installer.sh, line 246 -> main -d

[0;34m[1mImportant: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues[0m

------------------------------------------------------------------------------------------------
Could not install EMBA
```

2023-02-10 11:28 UTC, torabi12 commented
> ```
> �[1mInstalling libssl1.1 for mongodb!�[0m
> ------------------------------------------------------------------------------------------------
> Error detected - status code �[0;33m8�[0m
> Command:  �[0;33mecho -e "Command:  $ORANGE$BASH_COMMAND$NC"�[0m
> Location:  �[0;33m./installer/ID1_ubuntu_os.sh�[0m, line �[0;33m42�[0m
> Stack Trace:
>     [1] ID1_ubuntu_os(): ./installer/ID1_ubuntu_os.sh, line 42 -> ID1_ubuntu_os
>     [2] main(): ./installer.sh, line 246 -> main -d
> 
> �[0;34m�[1mImportant: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues�[0m
> 
> ------------------------------------------------------------------------------------------------
> Could not install EMBA
> ```

May I open an issue for EMBA for this?

2023-02-11 10:54 UTC, torabi12 commented
> I tried again the porter version and when I started the scan the browser was waiting a few sec and I got timeout: ![kép](https://user-images.githubusercontent.com/98665813/217320922-5c00f12c-7595-44b3-af04-85db3507a034.png)
> 
> I was just curious about its current state. OS: Ubuntu Server 22.04.1

I tested today again and it was working I did not get the above gateway error in EMBArk.
I only found that the "Associate" button dropped an error when I wanted to link the detailed view to an item in the drop down list. But I had only one item, maybe that is the problem.
![kép](https://user-images.githubusercontent.com/98665813/218254301-7dd81d26-ab79-4a6c-8c94-5715819ab3f4.png)

2023-02-15 17:39 UTC, m-1-k-3 approved these changes

2023-02-15 17:40 UTC, merged